# Generated by Django 3.1 on 2020-08-11 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_title', models.CharField(max_length=20)),
                ('f_ctime', models.DateTimeField(auto_now_add=True)),
                ('f_etime', models.DateTimeField(auto_now=True)),
                ('f_ecount', models.IntegerField(default=0)),
                ('trash_status', models.BooleanField(default=False)),
                ('share_status', models.BooleanField(default=False)),
                ('f_status', models.BooleanField(default=False)),
                ('f_dtime', models.DateTimeField(null=True)),
                ('read', models.IntegerField(default=1)),
                ('edit', models.IntegerField(default=1)),
                ('delete', models.IntegerField(default=1)),
                ('comment', models.IntegerField(default=1)),
                ('share', models.IntegerField(default=1)),
                ('t_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.team')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
