# Generated by Django 3.0.5 on 2020-08-13 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200812_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='f_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='account.File'),
        ),
    ]
