# Generated by Django 3.0.8 on 2020-08-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200817_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='m_type',
        ),
        migrations.AlterField(
            model_name='file',
            name='f_etime',
            field=models.DateTimeField(null=True),
        ),
    ]
