# Generated by Django 3.1 on 2020-08-11 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('tm_id', models.AutoField(primary_key=True, serialize=False)),
                ('join_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=1)),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.team')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
