# Generated by Django 3.0.5 on 2020-08-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200818_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='m_type',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
