# Generated by Django 3.1 on 2020-08-11 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_browserecords'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditHistory',
            fields=[
                ('ed_id', models.AutoField(primary_key=True, serialize=False)),
                ('edit_time', models.DateTimeField(auto_now_add=True)),
                ('f_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.file')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
