# Generated by Django 3.1 on 2020-08-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200819_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='intro',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
