# Generated by Django 3.0.3 on 2020-08-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200813_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='join_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
