# Generated by Django 3.0.3 on 2020-08-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200813_1443'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocImage',
        ),
    ]
