# Generated by Django 3.0.5 on 2020-08-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_team_intro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='m_type',
            new_name='m_title',
        ),
        migrations.AddField(
            model_name='message',
            name='f_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='t_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
