# Generated by Django 3.1 on 2020-08-11 17:34

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_myuser_u_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='f_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=100000, null=True),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('tmplt_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=100000, null=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('edit_count', models.IntegerField(default=0)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocImage',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_url', models.CharField(max_length=500)),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.file')),
            ],
        ),
    ]
