# Generated by Django 3.0.3 on 2020-08-13 15:02

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_delete_docimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocImage',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to=account.models.user_directory_path)),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.File')),
            ],
        ),
    ]
