# Generated by Django 3.0.5 on 2020-08-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200819_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='m_type',
            field=models.IntegerField(default=0),
        ),
    ]
