# Generated by Django 3.0.5 on 2020-08-19 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_message_m_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='f_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='account.File'),
        ),
    ]
