# Generated by Django 3.1 on 2020-08-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_docimage'),
        ('account', '0008_auto_20200813_1451'),
    ]

    operations = [
    ]
