# Generated by Django 3.0.3 on 2020-08-13 20:49

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_docimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='u_avatar',
            field=models.ImageField(default='default_avatar.jpg', upload_to=account.models.user_avatar_path),
        ),
    ]
