# Generated by Django 3.0.3 on 2020-08-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_merge_20200813_1524'),
        ('account', '0010_auto_20200813_2049'),
    ]

    operations = [
    ]
