# Generated by Django 3.1 on 2020-08-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_merge_20200814_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='f_content',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='content',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
