# Generated by Django 3.0.3 on 2020-08-14 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_merge_20200814_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='u_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
