# Generated by Django 3.1 on 2020-08-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_template_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='intro',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
